name: Generate formatted domains

on:
  push:
    paths:
      - domains.txt

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate file
        run: |
          sort -u domains.txt | sed 's/^/DOMAIN-SUFFIX,/' > domains-shadowrocket.txt

      - name: Commit result
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add domains-shadowrocket.txt
          git commit -m "Auto-generate domains-shadowrocket.txt" || true
          git push

